title: "Dimitris Papadopoulos"
description: "Professional CV"
theme: minima

# Project site (not user/org):
url: "https://aegeandp.github.io"
baseurl: "/Dimitris_PApadopoulos_CV"

header_pages:
  - cv.md

minima:
  skin: auto
